version: "3.4"
services:
    rabbitmq:
       hostname: rabbit1
       image: rabbitmq:3-management
       ports: 
       - "5672:5672" 
       - "15672:15672"
    redis:
       image: redis
       container_name: cache
       ports:
        - "6379:6379"

